plugins {
    id 'com.android.application'
}

android {
    namespace 'ru.dachafibonacci.glassclockwidget'
    compileSdk 35

    defaultConfig {
        applicationId 'ru.dachafibonacci.glassclockwidget.v8install'
        minSdk 26
        targetSdk 35
        versionCode 81
        versionName '8.1-install-fix'
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
        }
    }
}
