plugins {
    id 'com.android.application'
}

android {
    namespace 'ru.dachafibonacci.glassclockwidget'
    compileSdk 35

    defaultConfig {
        applicationId 'ru.dachafibonacci.glassclockwidget.v82resize'
        minSdk 26
        targetSdk 35
        versionCode 82
        versionName '8.2-resizable'
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
        }
    }
}
